spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/testdb
spring.datasource.username=root
spring.datasource.password=admin

jwt.secret=D8d8d7dHNDHNDND8768976DHGJGJ657675DJHhjghjgjJHGJGJH76786786DHdad98798797988jhkjkhkjhjkhJHJKHKJHJKasdadasd97124371239218HKJHLJKJHJKHKJ1923890182389102830921
jwt.expiration=3600000