spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.datasource.url=jdbc:oracle:thin:@10.110.10.90:1521:oracle
spring.datasource.username=IT326S03
spring.datasource.password=optimism88
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

jwt.secret=D8d8d7dHNDHNDND8768976DHGJGJ657675DJHhjghjgjJHGJGJH76786786DHdad98798797988jhkjkhkjhjkhJHJKHKJHJKasdadasd97124371239218HKJHLJKJHJKHKJ1923890182389102830921
jwt.expiration=3600000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=robertbobertson970@gmail.com
spring.mail.password=skmj hsiw vczm pmah
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true